title: Chinese Muslim Travel RAG Corpus
description: expertly curated articles covering Chinese Muslim travel
url: "https://salaamalykum.github.io"
baseurl: "/Chinese-Muslim-Travel"
theme: minima
defaults:
  -
    scope:
      path: "content"
    values:
      layout: "article"
